import type { NextPage } from "next";
import Head from "next/head";

const LandingPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vulpes Idiomas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vulpes_ico.svg" />
      </Head>
      <div>ABOUT</div>
    </>
  );
};

export default LandingPage;
